### ISSUE TITLE
wrek.org redirect

### ISSUE THREAD

**Issue by vertigoner** [zesoft23/zesoft23.github.io#1]
Hello Jack. I'm you're QA engineer. 
The link in "I currently run three shows on WREK Atlanta" currently points to https://zesoft23.github.io/www.wrek.org

😉

**Comment by zesoft23** [comment]
Noah!!!!
________________________________

**Comment by zesoft23** [comment]
Fixed

**Comment by vertigoner** [comment]
😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍
